name: LSIF
on:
  - push
jobs:
  lsif-go:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    strategy:
      matrix:
        root:
          - ''
          - lib
    steps:
      - uses: actions/checkout@v2
      - name: Generate LSIF data
        working-directory: ${{ matrix.root }}
        run: lsif-go --no-animation
      - name: Upload lsif-go dump
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.root }}-dump
          path: ${{ matrix.root }}/dump.lsif

  lsif-tsc-eslint:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    strategy:
      matrix:
        root:
          - branded
          - browser
          - shared
          - web
          - wildcard
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-scripts
      - name: Generate
        run: ./node_modules/.bin/gulp generate
      - name: Generate LSIF data
        working-directory: client/${{ matrix.root }}
        run: lsif-tsc -p . -o dump.lsif
      - name: Build TypeScript
        run: yarn run --ignore-engines build-ts
      - name: Generate LSIF data
        working-directory: client/${{ matrix.root }}
        run: yarn eslint -f lsif -o dump-lint.lsif
      - name: Upload lsif-tsc dump
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.root }}-dump
          path: ${{ matrix.root }}/dump.lsif
      - name: Upload lsif-eslint dump
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.root }}-dump-lint
          path: ${{ matrix.root }}/dump-lint.lsif

  lsif-go-upload:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    needs: lsif-go
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        endpoint:
          - https://sourcegraph.com/
          - https://k8s.sgdev.org/
          - https://demo.sourcegraph.com/
        experimental:
          - false
        root:
          - ''
          - lib
    steps:
      - name: Download lsif-go dump
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.root }}-dump
      - name: Upload lsif-go data to ${{ matrix.endpoint }}
        working-directory: ${{ matrix.root }}
        run: src lsif upload -no-progress -github-token=${{ secrets.GITHUB_TOKEN }} -f dump.lsif
        env:
          SRC_ENDPOINT: ${{ matrix.endpoint }}
        
  lsif-tsc-eslint-upload:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    needs: lsif-tsc-eslint
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    strategy:
      matrix:
        endpoint:
          - https://sourcegraph.com/
          - https://k8s.sgdev.org/
          - https://demo.sourcegraph.com/
        experimental:
          - false
        root:
          - branded
          - browser
          - shared
          - web
          - wildcard
    steps:
      - name: Download lsif-tsc dump
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.root }}-dump
      - name: Upload lsif-tsc data to ${{ matrix.endpoint }}
        working-directory: client/${{ matrix.root }}
        run: src lsif upload -no-progress -github-token=${{ secrets.GITHUB_TOKEN }} -f dump.lsif
        env:
          SRC_ENDPOINT: ${{ matrix.endpoint }}
      - name: Download lsif-eslint dump
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.root }}-dump-lint
      - name: Upload lsif-eslint data to ${{ matrix.endpoint }}
        working-directory: client/${{ matrix.root }}
        run: src lsif upload -no-progress -github-token=${{ secrets.GITHUB_TOKEN }} -f dump-lint.lsif
        env:
          SRC_ENDPOINT: ${{ matrix.endpoint }}
